version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn web_site_restaurant.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - network
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - network
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  network:
    external: true